# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/tags/v2.16.0/docs-v2/content/en/schemas/v4beta13.json
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: g5y
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  # dev builds, speedier dev loops, not for production
  - image: example.net/yolean/g5y-sidecar
    context: .
    docker:
      cliFlags:
      - --builder=k3s-buildkit
      - --output
      - type=image,push=false,unpack=false,store=true,oci-mediatypes=true,rewrite-timestamp=true
      - --progress=plain
      - --metadata-file=sidecar/target/buildkit-images.json
      dockerfile: sidecar.Dockerfile
      buildArgs:
        SOURCE_DATE_EPOCH: "0"
        # trust turbo workflows
        SKIP_TESTS: "true"
  - image: example.net/yolean/g5y-test-keycloak
    context: examples/oauth-keycloak/keycloak
    docker:
      cliFlags:
      - --builder=k3s-buildkit
      - --output
      - type=image,push=false,unpack=false,store=true,oci-mediatypes=true,rewrite-timestamp=true
      buildArgs:
        SOURCE_DATE_EPOCH: "0"
manifests:
  kustomize:
    paths:
    - examples/noauth
profiles:
- name: g5y-noauth
- name: g5y-oauth-keycloak
  manifests:
    kustomize:
      paths:
      - examples/oauth-keycloak
