# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/tags/v2.16.0/docs-v2/content/en/schemas/v4beta13.json
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: g5y
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: example.net/yolean/g5y-sidecar
    context: .
    docker:
      cliFlags:
      # https://github.com/turbokube/k3s-buildkit/
      - --builder
      - "g5y"
      - --output
      - "type=image"
      dockerfile: sidecar.Dockerfile
      buildArgs:
        # trust turbo workflows
        SKIP_TESTS: "true"
  - image: example.net/yolean/g5y-test-keycloak
    context: examples/oauth-keycloak/keycloak
    docker:
      cliFlags:
      # https://github.com/turbokube/k3s-buildkit/
      - --builder
      - "g5y"
      - --output
      - "type=image"
manifests:
  kustomize:
    paths:
    - examples/noauth
profiles:
- name: load
  manifests:
    kustomize:
      paths:
      - setup/skaffold-load
- name: g5y-noauth
- name: g5y-oauth-keycloak
  manifests:
    kustomize:
      paths:
      - examples/oauth-keycloak
