apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxied
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  publishNotReadyAddresses: false
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8080
