# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

# Default values for ai-gateway-helm.

extProc:
  repository: docker.io/envoyproxy/ai-gateway-extproc
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # One of "info", "debug", "trace", "warn", "error", "fatal", "panic".
  logLevel: info

