# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-g5y

resources:
- echo-deployment.yaml
- echo-service-headless.yaml
- echo-service.yaml
- external-gateway.yaml
- external-http-route.yaml
- g5y-deployment.yaml
- g5y-service-headless.yaml

secretGenerator:
- name: gatewayconfig
  files:
  - envoy.yaml.template=envoy.g5y.yaml
- name: gatewayparams
  literals: []
