# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/v1.27.9/cronjob.json
# A cronjob because we don't want any pods to be scheduled
apiVersion: batch/v1
kind: CronJob
metadata:
  name: all-images
spec:
  schedule: "0 0 29 2 1" # https://stackoverflow.com/a/58670460/113009
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: g5y-sidecar
            image: example.net/yolean/g5y-sidecar
            command:
            - sleep
            - infinity
          - name: g5y-test-keycloak
            image: example.net/yolean/g5y-test-keycloak
            command:
            - sleep
            - infinity
          restartPolicy: Never
